baseURL = "https://funny-fudge-7159b4.netlify.app/"
languageCode = "en-us"
theme = "hyde"
title = "ashley"
[params]
  description = "testing description"
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = "theme-base-0c"
